config/routes.rb
Prueba2::Application.routes.draw do
  
  match '/rate' => 'rater#create', :as => 'rate'

  resources :rates

  

  

  get "activities/index"

  get 'activities/notificaciones'

  match 'dashboard' => 'dashboard#index'

  
  resources :investments
  resources :activities
  resources :profiles 
  
  resources :startups do
  
   
     collection do
      get :random
    end

    resources :investments
    resources :activities    
    resources :members do
 
       get :autocomplete_profiles_name, :on => :collection
    end
 
    resources :comments
  end

 

  match ':controller(/:action(/:id))(.:format)'

 
  

   root :to => 'inicio#show'

  match "game" => "dashboard#game"
    

  
end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
	    # Define abilities for the passed in user here. For example:
   user ||= User.new # guest user
    
    if user.role == "author"
      can :manage, :all
    else
      can :read, :all
    
    end


    

 

end  


end
  

app/models/comment.rb
class Comment < ActiveRecord::Base
  

  include PublicActivity::Common
  


  belongs_to :startup
  attr_accessible :body, :commenter ,:startup_id

  


end

app/models/investment.rb
class Investment < ActiveRecord::Base

include PublicActivity::Common

  belongs_to :user
  belongs_to :startup
  attr_accessible :vcmoney
end

app/models/member.rb
class Member < ActiveRecord::Base
  

  belongs_to :profile
  belongs_to :startup
  belongs_to :user
  
  attr_accessible :job, :mtype , :user_id ,:startup_id ,:email ,:name
end

app/models/profile.rb
class Profile < ActiveRecord::Base

belongs_to :user
attr_accessible :biography, :country, :email, :fullname , :user_id , :avatar


include PublicActivity::Model

validates :fullname, :presence =>true
validates :country,  :presence =>true
validates :email,  :presence =>true
validates :user_id, :uniqueness => true



mount_uploader :avatar, AvatarUploader

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
  
  attr_accessible :rate, :dimension
  
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true 
end

app/models/startup.rb
class Startup < ActiveRecord::Base

include PublicActivity::Common

letsrate_rateable "video", "name", "logo" , "website" , "idea" , "pitch"

include Rails.application.routes.url_helpers
attr_accessible :name, :video, :vmoney , :website ,:founder , :description ,:website , :category , :revenue , :stage ,:country , :semail , :avatar, :posidea , :negidea , :postext , :negtext , :poswebsite , :negwebsite , :poslogo , :neglogo ,:posvideo , :negvideo 


has_many :members
has_many :users , :through => :members
has_many :comments
#has_many :activities #comentado para el uso de la gema publicactivity
has_many :investments

mount_uploader :avatar, AvatarUploader

extend FriendlyId
friendly_id :name, use: [:slugged , :history]

validates :name, :presence =>true
validates :description,  :presence =>true
validates :semail,  :presence =>true
validates :category, :presence => true

validates :stage, :presence => true
validates :revenue, :presence =>true
validates :country,  :presence =>true


#falta uniqueness de website y name y email



def self.search(search)
  if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
end



end

app/models/ubadge.rb
class Ubadge < ActiveRecord::Base
  belongs_to :user
  attr_accessible :advangel, :earlyadapt, :feedmaster, :ffather, :knowit, :moneywise, :vetinvestor, :voiceofwisdom, :user_id

  ##recordar borar el user id despues
end

app/models/user.rb
class User < ActiveRecord::Base
   
   #require "BCrypt"

   include Clearance::User
   
   attr_accessible :role, :name

   letsrate_rater
  # has_and_belongs_to_many :roles
   has_one :ubadge
   has_one :profile
   has_many :members
   has_many :startups , :through => :members
   


 ROLES = %w[admin moderator author banned]






end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController


before_filter :authorize

def new

@investments = Investment.new

@startups = Startup.find(params[:startup_id])
 

end

def create


#IMPORTANTE AGREGAR EL CHEQUEO PARA VER CUANTA PLATA TIENE EL USER DISPONIBLE!



@startups= Startup.find(params[:startup_id])

#el chequeo 
@user = Profile.find_by_user_id(current_user.id)


# buscar usuario , compararlo con los member de la startup


@member = Member.where(:profile_id=>current_user.id , :startup_id=> @startups.id)

#chequeo de que usuario no invierta en si mismo

if @member == []



@investment = Investment.new(params[:investment])

if @user.wallet >= @investment.vcmoney  && @investment.vcmoney >= 20000 #si el user tiene plata


     @investment.user_id = current_user.id
     @investment.startup_id = @startups.id

  



   if @investment.save

 	  @startups.vmoney +=  @investment.vcmoney

   	@startups.update_attribute(:vmoney, @startups.vmoney)
    @user.update_attribute(:wallet , @user.wallet - @investment.vcmoney )

    @profile = Profile.find_by_user_id(current_user.id)
    @investment.create_activity :create , owner: @profile 
    redirect_to @startups 

     else

    render "new"
  
     end 

  else 


   flash[:notice] = "You dont have that money check ur wallet at your profile"  #puede ser mejorado mostrando en el momento de invertir mostrar la billetera
      redirect_to dashboard_path 
   

  end

else
flash[:notice] = "Barza COMO INVIERTES EN TI MISMO!!! PIERDES 10MIL"  #puede ser mejorado mostrando en el momento de invertir mostrar la billetera
      redirect_to dashboard_path 
   
   

end #

end







def myinvestments





@my = Investment.where("user_id = ?", params[:id])

@startups_ids = @my.collect(&:startup_id)

@startups = Startup.find(@startups_ids)


end


def index

@investments = Investment.all

end


end

app/controllers/rater_controller.rb
class RaterController < ApplicationController 
  
  def create                                  
    if current_user.present?
      obj = eval "#{params[:klass]}.find(#{params[:id]})"     
      if params[:dimension].present?
        obj.rate params[:score].to_i, current_user.id, "#{params[:dimension]}"       
      else
        obj.rate params[:score].to_i, current_user.id 
      end
      
      render :json => true 
    else
      render :json => false        
    end
  end                                        
  
  
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/investment_helper.rb
module InvestmentHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sbadge_helper.rb
module SbadgeHelper
end

app/helpers/sbadges_helper.rb
module SbadgesHelper
end

app/helpers/vcdashboard_helper.rb
module VcdashboardHelper
end

app/views/investments/_form.html.erb
<%= simple_form_for @investment, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :user_id %>
  <%= f.input :startup_id %>
  <%= f.input :vcmoney %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                investments_path, :class => 'btn' %>
  </div>
<% end %>

app/views/investments/_investment.html.erb
<div class= "row">

<%= simple_form_for([@startups, @startups.investments.build]) do |f| %>
 

<%= f.input_field :vcmoney , :label =>"amount" , :value =>" 20000" , :id=>"inputi"%>


<%= f.button :submit, :class => 'nice small radius blue button' , :value=>"Invest"  %>
 
 <% end %>
</div>

app/views/investments/edit.html.erb
<%- model_class = Investment -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/investments/index.html.erb
<%- model_class = Investment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:startup_id) %></th>
      <th><%= model_class.human_attribute_name(:vcmoney) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @investments.each do |investment| %>
      <tr>
        <td><%= link_to investment.id, investment_path(investment) %></td>
        <td><%= investment.user_id %></td>
        <td><%= investment.startup_id %></td>
        <td><%= investment.vcmoney %></td>
        <td><%=l investment.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_investment_path(investment), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      investment_path(investment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_investment_path,
            :class => 'btn btn-primary' %>

app/views/investments/myinvestments.html.erb


<div class="container">
<h1> My investments </h1>
<% @startups.each  do |startup| %>
<div class= "row">


	<div class="span6">


	<%= image_tag startup.avatar_url ,:style=>"width:100px;height:100px;"%>



	</div>

	<div class="span6"><h2 class ="subheader"><%= link_to startup.name , startup_path(startup) %> </h2></div>


</div><br>
<% end %>


</div>


app/views/investments/new.html.erb
<%- model_class = Investment -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/investments/show.html.erb
<%- model_class = Investment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @investment.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:startup_id) %>:</strong></dt>
  <dd><%= @investment.startup_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vcmoney) %>:</strong></dt>
  <dd><%= @investment.vcmoney %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              investments_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_investment_path(@investment), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              investment_path(@investment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>