config/routes.rb
Prueba2::Application.routes.draw do
  
  match '/rate' => 'rater#create', :as => 'rate'

  resources :rates

  

  

  get "activities/index"

  get 'activities/notificaciones'

  match 'dashboard' => 'dashboard#index'

  
  resources :investments
  resources :activities
  resources :profiles 
  
  resources :startups do
  
   
     collection do
      get :random
    end

    resources :investments
    resources :activities    
    resources :members do
 
       get :autocomplete_profiles_name, :on => :collection
    end
 
    resources :comments
  end

 

  match ':controller(/:action(/:id))(.:format)'

 
  

   root :to => 'inicio#show'

  match "game" => "dashboard#game"
    

  
end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
	    # Define abilities for the passed in user here. For example:
   user ||= User.new # guest user
    
    if user.role == "author"
      can :manage, :all
    else
      can :read, :all
    
    end


    

 

end  


end
  

app/models/comment.rb
class Comment < ActiveRecord::Base
  

  include PublicActivity::Common
  


  belongs_to :startup
  attr_accessible :body, :commenter ,:startup_id

  


end

app/models/investment.rb
class Investment < ActiveRecord::Base

include PublicActivity::Common

  belongs_to :user
  belongs_to :startup
  attr_accessible :vcmoney
end

app/models/member.rb
class Member < ActiveRecord::Base
  

  belongs_to :profile
  belongs_to :startup
  belongs_to :user
  
  attr_accessible :job, :mtype , :user_id ,:startup_id ,:email ,:name
end

app/models/profile.rb
class Profile < ActiveRecord::Base

belongs_to :user
attr_accessible :biography, :country, :email, :fullname , :user_id , :avatar


include PublicActivity::Model

validates :fullname, :presence =>true
validates :country,  :presence =>true
validates :email,  :presence =>true
validates :user_id, :uniqueness => true



mount_uploader :avatar, AvatarUploader

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
  
  attr_accessible :rate, :dimension
  
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true 
end

app/models/startup.rb
class Startup < ActiveRecord::Base

include PublicActivity::Common

letsrate_rateable "video", "name", "logo" , "website" , "idea" , "pitch"

include Rails.application.routes.url_helpers
attr_accessible :name, :video, :vmoney , :website ,:founder , :description ,:website , :category , :revenue , :stage ,:country , :semail , :avatar, :posidea , :negidea , :postext , :negtext , :poswebsite , :negwebsite , :poslogo , :neglogo ,:posvideo , :negvideo 


has_many :members
has_many :users , :through => :members
has_many :comments
#has_many :activities #comentado para el uso de la gema publicactivity
has_many :investments

mount_uploader :avatar, AvatarUploader

extend FriendlyId
friendly_id :name, use: [:slugged , :history]

validates :name, :presence =>true
validates :description,  :presence =>true
validates :semail,  :presence =>true
validates :category, :presence => true

validates :stage, :presence => true
validates :revenue, :presence =>true
validates :country,  :presence =>true


#falta uniqueness de website y name y email



def self.search(search)
  if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
end



end

app/models/ubadge.rb
class Ubadge < ActiveRecord::Base
  belongs_to :user
  attr_accessible :advangel, :earlyadapt, :feedmaster, :ffather, :knowit, :moneywise, :vetinvestor, :voiceofwisdom, :user_id

  ##recordar borar el user id despues
end

app/models/user.rb
class User < ActiveRecord::Base
   
   #require "BCrypt"

   include Clearance::User
   
   attr_accessible :role, :name

   letsrate_rater
  # has_and_belongs_to_many :roles
   has_one :ubadge
   has_one :profile
   has_many :members
   has_many :startups , :through => :members
   


 ROLES = %w[admin moderator author banned]






end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController

before_filter :authorize, except: [:show] 

def index

    
     @startups = Startup.search(params[:search])
   end



  def new
  

     @profile = Profile.find_by_user_id(current_user.id)

   if @profile == nil
   
     flash[:notice] = "You have no profile please create one before creating a startup"
     redirect_to new_profile_path(@profile) 
    
    else 

    @startup = Startup.new
  
  end

  end

  def show
   
   if @startup = Startup.find(params[:id])


   else

    redirect_to dashboard_path

  end
    
  end

  def create

    @startup  = Startup.new(params[:startup])
    @startup.vmoney = 0 


    #CHEQUEO DE PERFIL


    @profile = Profile.find_by_user_id(current_user.id)

   if @profile == nil
   
     flash[:notice] = "You have no profile please create one please create one before creating a startup"
    redirect_to new_profile_path(@profile) 

   #hay q inicializar el vmoney si
   
   else


    if @startup.save 

      #agregar el member
      @member = Member.new
      @member.mtype = "founder"
      @member.job ="CEO"


      
     
      @member.email = @profile.email
      @member.name = @profile.fullname
      @member.profile_id =@profile.id
      @member.startup_id = @startup.id
      @member.user_id = current_user.id
      @member.save
      redirect_to @startup
    else
      flash[:notice] = "Fill the needed data"  #puede ser mejorado mostrando en el momento de invertir mostrar la billetera
      redirect_to dashboard_path 
   
    end #fin del grabado



end # fin de ciclo para crear






  end


def todo

@startup = Startup.all

end



def search

 
 
end





def edit 


  @startup = Startup.find(params[:id])
  
     
end




def update
    
    @startup = Startup.find(params[:id])
    
    if @startup.update_attributes(params[:startup])
       @investment.create_activity :update , owner: @profile 
      redirect_to @startup
    else
      render :edit
    end


end



def destroy
 @startup = Startup.find(params[:id])
    @startup.destroy
redirect_to :dashboard
    #respond_to do |format|
     # format.html { redirect_to dashboard_url }
      #format.json { head :no_content }
#end
end


def mystartups

  

  #@members = Member.find_by_user_id(params[:id])
 # @startups =Startup.find(@members.startup_id)
  
@members = Member.where("user_id = ?", params[:id])

@startups_ids = @members.collect(&:startup_id)

@startups = Startup.find(@startups_ids)


end






 def showguest





 end




 def feedback


@startupf = Startup.new

@startupf.posvideo = :posvideo





 end


 




end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/investment_helper.rb
module InvestmentHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sbadge_helper.rb
module SbadgeHelper
end

app/helpers/sbadges_helper.rb
module SbadgesHelper
end

app/helpers/vcdashboard_helper.rb
module VcdashboardHelper
end

app/views/startups/_form.html.erb
<%= simple_form_for @startup do |f|  %>



  <%= f.input :name %><br><br>
  <%= f.input :video %><br><br>
  <%= f.input :description %><br>
  <%= f.input :website %><br><br>


 * Stage<br>
 <%= f.select(:stage, [["Concept"], ["Working prototype in development"], ["Functional Product with Users"], ["Scaling Sales"]] )  %><br><br>
  * Category<br>
  <%= f.select(:category, [["Consulting"], ["E-commerce"], ["Education"], ["Energy & Clean Tech"] , ["Finance"], ["Healthcare & Biotechnology"], ["IT & Enterprise Software"], ["Import/Export"],["Mobile & Wireless"],["Natural Resources - mining, food, lumber, etc, "], ["Media"] , ["Social Enterprise"], ["Social Media/Social Network"], ["Tourism"], ["Sorry, we do not fit into any category above"]] ) %> <br><br>
  <%= f.input :country %><br><br>
  <%= f.input :revenue %><br><br>
  <%= f.input :semail %><br><br>

 <label > Upload Photo</label>
<%= f.file_field :avatar ,  :class => "btn"  %>


 <br>
 <br>
 <br>

    




<%= f.button :submit , :class => 'nice small radius blue button' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                startups_path, :class => 'button' %>

  <% end %>

app/views/startups/_startup.html.erb




<h2 class="subheader"> lista de startups </h2>

app/views/startups/edit.html.erb
<div class="container">


<%- model_class = @startup.class -%>
<h3 class="subheader"><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h3>
<%= render :partial => 'form' %>



<h4><%= link_to "Add Member", new_startup_member_path(@startup ) %></h4>


</div>

app/views/startups/index.html.erb
<div style="padding-left:1%;padding-rigth:1%;">
<%- model_class = Startup.new.class -%>
<h1 class="subheader"><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:video) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:vmoney) %></th>
      <th><%= model_class.human_attribute_name(:website) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:stage) %></th>
      <th><%= model_class.human_attribute_name(:revenue) %></th>
      <th><%= model_class.human_attribute_name(:semail) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @startups.each do |startup| %>
      <tr>
        <td><%= link_to startup.id, startup_path(startup) %></td>
        <td><%= startup.name %></td>
        <td><%= startup.video %></td>
        <td><%= startup.description[0,100] %></td>
        <td><%= startup.vmoney %></td>
        <td><%= startup.website %></td>
        <td><%= startup.category %></td>
        <td><%= startup.country %></td>
        <td><%= startup.stage %></td>
        <td><%= startup.revenue %></td>
        <td><%= startup.semail %></td>
        <td><%=l startup.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_startup_path(startup), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      startup_path(startup),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>

          <%= link_to "New activity ", new_startup_activity_path(startup) %>           
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_startup_path,
            :class => 'btn btn-primary' %>




<br><br>


<% form_tag do  %>
     <%= submit_tag :class => 'btn btn-primary'%>
  </p>
<% end %>

</div>

app/views/startups/mystartups.html.erb
<div class="container">
<div class="row-fluid">
<h2 class="subheader" > My startups </h2>






<% @startups.each  do |startup| %>

<tr>
<td><h4 class="subheader" ><%= startup.name %></h4> </td>

<td > <%= link_to "Show" , startup_path(startup) , :class=>"btn" ,:style=>"green" %> </td>
<% if can?  :update, startup %>
<td><%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_startup_path(startup), :class => 'btn' %></td><% end %>
   


<% if can?  :create, startup.members %>  
<td><%= link_to "Add Member", new_startup_member_path(startup ) ,:class=>"btn" %> </td>
 <% end %>

<% if can?  :destroy, startup %>  
<td>       <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      startup_path(startup),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn' %></td><% end %>



 </tr>
<% end %>

</div><br> <br></div>

app/views/startups/new.html.erb
<div class="row-fluid"><div class="container">
<div class="span3" style="background-color:#f5f5f5;">
<button class="btn btn-block btn-primary btn-large disabled"> New Startup </button>
<br><center>
<%= render :partial => 'form' %></center></div>
<div class="span9"></div>



</div></div>

app/views/startups/show.html.erb
<div class="container">
  

  <div class="row-fluid">

    
    <div class="span8">

        <div class="row">

          <div class="span2"> 
            <img src= <%= @startup.avatar_url%> style="width:100px;height:100px;">
          </div>  
          <div class="span10">  
            <h1 style="color:#0088cc;"><%= @startup.name%></h1>
            <p style="color:#0088cc;"><%= @startup.category%> &nbsp;&nbsp;<i class="icon-home"></i>&nbsp;&nbsp; <%= @startup.country%> </p>
          </div>  

        </div><!-- fin del row de head del span8-->

        <div class="row">
          <br>
          <iframe src="http://player.vimeo.com/video/<%= @startup.video %>" width="100%" height="300px" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>

          <br>


          <ul class="nav nav-tabs">
            <li><a href="#home" data-toggle="tab"><h4 style="color:#0088cc;">Startup Pitch</h3>
            </a></li>
            <li><a href="#profile" data-toggle="tab"><h4 style="color:#0088cc;">Members</h3></a>
            </li>
            
          </ul>


          <div class="tab-content">
            <div class="tab-pane active" id="home"><%= @startup.description %> </div>
            <div class="tab-pane" id="profile"><%= render @startup.members %></div>
            
          </div>

          <H3>_________________________________________________________</H3>

          <h4 class="subheader"> FeedBack </h4>
   
            <%= render @startup.comments %> <br>
  

          <% if signed_in? %>
           <h4 class="subheader"> Comment </h4>
           
            <%= form_for([ @startup, @startup.comments.build]) do |f| %>
  
            <%= f.hidden_field :commenter , :value => current_user.email  %>
  

            <%= f.text_area :body , :style=>"height:74px;width:534px;"%>
            <%= f.hidden_field :startup_id , :value => @startup.id  %><br> 
  
   
            <%= f.button :submit , :class => 'btn' , :id =>"Comment" %>
  
            <% end %> <!--fin del form -->

             <%end%><!--fin del if -->




         </div> <!-- fin del contenido-->

    </div>

    <div class="span4">

       
                Idea: <%= rating_for @startup, "idea" %>
               Website : <%= rating_for @startup, "website" %>
               Name : <%= rating_for @startup, "name" %>
               Logo : <%= rating_for @startup, "logo" %>
               Pitch <%= rating_for @startup, "pitch" %>
               Video : <%= rating_for @startup, "video" %>


    </div>






  </div> <!-- fin del row de todo el contenido-->
</div> <!-- fin del container-->