config/routes.rb
Prueba2::Application.routes.draw do
  
  match '/rate' => 'rater#create', :as => 'rate'

  resources :rates

  

  

  get "activities/index"

  get 'activities/notificaciones'

  match 'dashboard' => 'dashboard#index'

  
  resources :investments
  resources :activities
  resources :profiles 
  
  resources :startups do
  
   
     collection do
      get :random
    end

    resources :investments
    resources :activities    
    resources :members do
 
       get :autocomplete_profiles_name, :on => :collection
    end
 
    resources :comments
  end

 

  match ':controller(/:action(/:id))(.:format)'

 
  

   root :to => 'inicio#show'

  match "game" => "dashboard#game"
    

  
end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
	    # Define abilities for the passed in user here. For example:
   user ||= User.new # guest user
    
    if user.role == "author"
      can :manage, :all
    else
      can :read, :all
    
    end


    

 

end  


end
  

app/models/comment.rb
class Comment < ActiveRecord::Base
  

  include PublicActivity::Common
  


  belongs_to :startup
  attr_accessible :body, :commenter ,:startup_id

  


end

app/models/investment.rb
class Investment < ActiveRecord::Base

include PublicActivity::Common

  belongs_to :user
  belongs_to :startup
  attr_accessible :vcmoney
end

app/models/member.rb
class Member < ActiveRecord::Base
  

  belongs_to :profile
  belongs_to :startup
  belongs_to :user
  
  attr_accessible :job, :mtype , :user_id ,:startup_id ,:email ,:name
end

app/models/profile.rb
class Profile < ActiveRecord::Base

belongs_to :user
attr_accessible :biography, :country, :email, :fullname , :user_id , :avatar


include PublicActivity::Model

validates :fullname, :presence =>true
validates :country,  :presence =>true
validates :email,  :presence =>true
validates :user_id, :uniqueness => true



mount_uploader :avatar, AvatarUploader

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
  
  attr_accessible :rate, :dimension
  
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true 
end

app/models/startup.rb
class Startup < ActiveRecord::Base

include PublicActivity::Common

letsrate_rateable "video", "name", "logo" , "website" , "idea" , "pitch"

include Rails.application.routes.url_helpers
attr_accessible :name, :video, :vmoney , :website ,:founder , :description ,:website , :category , :revenue , :stage ,:country , :semail , :avatar, :posidea , :negidea , :postext , :negtext , :poswebsite , :negwebsite , :poslogo , :neglogo ,:posvideo , :negvideo 


has_many :members
has_many :users , :through => :members
has_many :comments
#has_many :activities #comentado para el uso de la gema publicactivity
has_many :investments

mount_uploader :avatar, AvatarUploader

extend FriendlyId
friendly_id :name, use: [:slugged , :history]

validates :name, :presence =>true
validates :description,  :presence =>true
validates :semail,  :presence =>true
validates :category, :presence => true

validates :stage, :presence => true
validates :revenue, :presence =>true
validates :country,  :presence =>true


#falta uniqueness de website y name y email



def self.search(search)
  if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
end



end

app/models/ubadge.rb
class Ubadge < ActiveRecord::Base
  belongs_to :user
  attr_accessible :advangel, :earlyadapt, :feedmaster, :ffather, :knowit, :moneywise, :vetinvestor, :voiceofwisdom, :user_id

  ##recordar borar el user id despues
end

app/models/user.rb
class User < ActiveRecord::Base
   
   #require "BCrypt"

   include Clearance::User
   
   attr_accessible :role, :name

   letsrate_rater
  # has_and_belongs_to_many :roles
   has_one :ubadge
   has_one :profile
   has_many :members
   has_many :startups , :through => :members
   


 ROLES = %w[admin moderator author banned]






end

app/controllers/rater_controller.rb
class RaterController < ApplicationController 
  
  def create                                  
    if current_user.present?
      obj = eval "#{params[:klass]}.find(#{params[:id]})"     
      if params[:dimension].present?
        obj.rate params[:score].to_i, current_user.id, "#{params[:dimension]}"       
      else
        obj.rate params[:score].to_i, current_user.id 
      end
      
      render :json => true 
    else
      render :json => false        
    end
  end                                        
  
  
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rates }
    end
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
    @rate = Rate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/new
  # GET /rates/new.json
  def new
    @rate = Rate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/1/edit
  def edit
    @rate = Rate.find(params[:id])
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(params[:rate])

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'Rate was successfully created.' }
        format.json { render json: @rate, status: :created, location: @rate }
      else
        format.html { render action: "new" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rates/1
  # PUT /rates/1.json
  def update
    @rate = Rate.find(params[:id])

    respond_to do |format|
      if @rate.update_attributes(params[:rate])
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate = Rate.find(params[:id])
    @rate.destroy

    respond_to do |format|
      format.html { redirect_to rates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/investment_helper.rb
module InvestmentHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sbadge_helper.rb
module SbadgeHelper
end

app/helpers/sbadges_helper.rb
module SbadgesHelper
end

app/helpers/vcdashboard_helper.rb
module VcdashboardHelper
end

app/views/rates/_form.html.erb
<%= simple_form_for(@rate) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :startup %>
    <%= f.input :name %>
    <%= f.input :website %>
    <%= f.input :video %>
    <%= f.input :logo %>
    <%= f.input :text %>
    <%= f.input :idea %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<h1>Editing rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

app/views/rates/index.html.erb
<h1>Listing rates</h1>

<table>
  <tr>
    <th>User</th>
    <th>Startup</th>
    <th>Name</th>
    <th>Website</th>
    <th>Video</th>
    <th>Logo</th>
    <th>Text</th>
    <th>Idea</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rates.each do |rate| %>
  <tr>
    <td><%= rate.user %></td>
    <td><%= rate.startup %></td>
    <td><%= rate.name %></td>
    <td><%= rate.website %></td>
    <td><%= rate.video %></td>
    <td><%= rate.logo %></td>
    <td><%= rate.text %></td>
    <td><%= rate.idea %></td>
    <td><%= link_to 'Show', rate %></td>
    <td><%= link_to 'Edit', edit_rate_path(rate) %></td>
    <td><%= link_to 'Destroy', rate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rate', new_rate_path %>

app/views/rates/new.html.erb
<h1>New rate</h1>

<%= render 'form' %>

<%= link_to 'Back', rates_path %>

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @rate.user %>
</p>

<p>
  <b>Startup:</b>
  <%= @rate.startup %>
</p>

<p>
  <b>Name:</b>
  <%= @rate.name %>
</p>

<p>
  <b>Website:</b>
  <%= @rate.website %>
</p>

<p>
  <b>Video:</b>
  <%= @rate.video %>
</p>

<p>
  <b>Logo:</b>
  <%= @rate.logo %>
</p>

<p>
  <b>Text:</b>
  <%= @rate.text %>
</p>

<p>
  <b>Idea:</b>
  <%= @rate.idea %>
</p>


<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>