config/routes.rb
Prueba2::Application.routes.draw do
  
  match '/rate' => 'rater#create', :as => 'rate'

  resources :rates

  

  

  get "activities/index"

  get 'activities/notificaciones'

  match 'dashboard' => 'dashboard#index'

  
  resources :investments
  resources :activities
  resources :profiles 
  
  resources :startups do
  
   
     collection do
      get :random
    end

    resources :investments
    resources :activities    
    resources :members do
 
       get :autocomplete_profiles_name, :on => :collection
    end
 
    resources :comments
  end

 

  match ':controller(/:action(/:id))(.:format)'

 
  

   root :to => 'inicio#show'

  match "game" => "dashboard#game"
    

  
end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
	    # Define abilities for the passed in user here. For example:
   user ||= User.new # guest user
    
    if user.role == "author"
      can :manage, :all
    else
      can :read, :all
    
    end


    

 

end  


end
  

app/models/comment.rb
class Comment < ActiveRecord::Base
  

  include PublicActivity::Common
  


  belongs_to :startup
  attr_accessible :body, :commenter ,:startup_id

  


end

app/models/investment.rb
class Investment < ActiveRecord::Base

include PublicActivity::Common

  belongs_to :user
  belongs_to :startup
  attr_accessible :vcmoney
end

app/models/member.rb
class Member < ActiveRecord::Base
  

  belongs_to :profile
  belongs_to :startup
  belongs_to :user
  
  attr_accessible :job, :mtype , :user_id ,:startup_id ,:email ,:name
end

app/models/profile.rb
class Profile < ActiveRecord::Base

belongs_to :user
attr_accessible :biography, :country, :email, :fullname , :user_id , :avatar


include PublicActivity::Model

validates :fullname, :presence =>true
validates :country,  :presence =>true
validates :email,  :presence =>true
validates :user_id, :uniqueness => true



mount_uploader :avatar, AvatarUploader

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
  
  attr_accessible :rate, :dimension
  
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true 
end

app/models/startup.rb
class Startup < ActiveRecord::Base

include PublicActivity::Common

letsrate_rateable "video", "name", "logo" , "website" , "idea" , "pitch"

include Rails.application.routes.url_helpers
attr_accessible :name, :video, :vmoney , :website ,:founder , :description ,:website , :category , :revenue , :stage ,:country , :semail , :avatar, :posidea , :negidea , :postext , :negtext , :poswebsite , :negwebsite , :poslogo , :neglogo ,:posvideo , :negvideo 


has_many :members
has_many :users , :through => :members
has_many :comments
#has_many :activities #comentado para el uso de la gema publicactivity
has_many :investments

mount_uploader :avatar, AvatarUploader

extend FriendlyId
friendly_id :name, use: [:slugged , :history]

validates :name, :presence =>true
validates :description,  :presence =>true
validates :semail,  :presence =>true
validates :category, :presence => true

validates :stage, :presence => true
validates :revenue, :presence =>true
validates :country,  :presence =>true


#falta uniqueness de website y name y email



def self.search(search)
  if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
end



end

app/models/ubadge.rb
class Ubadge < ActiveRecord::Base
  belongs_to :user
  attr_accessible :advangel, :earlyadapt, :feedmaster, :ffather, :knowit, :moneywise, :vetinvestor, :voiceofwisdom, :user_id

  ##recordar borar el user id despues
end

app/models/user.rb
class User < ActiveRecord::Base
   
   #require "BCrypt"

   include Clearance::User
   
   attr_accessible :role, :name

   letsrate_rater
  # has_and_belongs_to_many :roles
   has_one :ubadge
   has_one :profile
   has_many :members
   has_many :startups , :through => :members
   


 ROLES = %w[admin moderator author banned]






end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json

  before_filter :authorize , except: [:show]

  autocomplete :profiles, :column_name => 'fullname',  :full => true 
  
  def index

    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end

  end

  def show 

    #@member =Member.find(params[:id])

    @member = Member.new
   

  end

  def _member
   
   @member = Member.new


  end

  def new 
  
  
 @members = Member.new
 @startups= Startup.find(params[:startup_id])
 
 end


 def create

  @startups= Startup.find(params[:startup_id])

  @member = Member.new(params[:member])

  @profile = Profile.find_by_email(@member.email)

  @member.startup_id = @startups.id

  @member.user_id = @profile.user_id

  @member.profile_id = @profile.id

  @member.name = @profile.fullname

  if @member.save

  redirect_to @startups

  else

  render "new"
  
  end 

 end


 


 def edit

  @members = Member.find(params[:id])
  @startups =Startup.find(@members.startup_id)


 end 


 def update


   @members = Member.find(params[:id])
   @startups =Startup.find(@members.startup_id)

    if @members.update_attributes(params[:members])
      redirect_to @startups
    else
      render :edit
    end


 end

def destroy

     
@member = Member.find(params[:id])    
@member.destroy
redirect_to "/startups/mystartups/#{current_user.id}"
end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController 
  
  def create                                  
    if current_user.present?
      obj = eval "#{params[:klass]}.find(#{params[:id]})"     
      if params[:dimension].present?
        obj.rate params[:score].to_i, current_user.id, "#{params[:dimension]}"       
      else
        obj.rate params[:score].to_i, current_user.id 
      end
      
      render :json => true 
    else
      render :json => false        
    end
  end                                        
  
  
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/investment_helper.rb
module InvestmentHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sbadge_helper.rb
module SbadgeHelper
end

app/helpers/sbadges_helper.rb
module SbadgesHelper
end

app/helpers/vcdashboard_helper.rb
module VcdashboardHelper
end

app/views/members/_form.html.erb
<div class= "row">

<%= simple_form_for([@startups, @startups.members.build]) do |f| %>
 

<%= f.input :name, :url =>autocomplete_profiles_name_startup_members_path, :as=>:autocomplete %>




<%= f.input :email   %>


 <%= f.input :job %>


 <%= f.input :mtype , :label =>'Member type' , :placeholder => 'Cofounder / Member' %>
 
 <%= f.button :submit, :class => 'nice small radius blue button'  %>
 
 <% end %>
</div>

app/views/members/_member.html.erb

<!-- este es el que muestra los members en show -->


<p>
      <%= link_to member.name  , :controller => :profiles , :action => :show , :id=> member.profile_id  %> &nbsp;&nbsp;&nbsp;&nbsp; <%= member.job %> / <%= member.mtype %>

</p><br>


 

 

app/views/members/edit.html.erb
<div class="container">
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
</div>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table class="table table-striped">
  <tr>
    <th>Job</th>
    <th>Member type</th>
    <th>Startup id</th>
    <th>Profile id</th>
    <th>Email</th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.job %></td>
    <td><%= member.mtype %></td>
    <td><%= member.startup_id %></td>
     <td><%= member.profile_id %></td>
     <td><%= member.email %></td>

     <td>
     <%= link_to "edit" , edit_startup_member_path(member.startup_id ,member)%>

     <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      startup_member_path(member.startup_id ,member),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>


   </td>

  </tr>
<% end %>
</table>

<br />

app/views/members/new.html.erb
 <h2 class="subheader">New Member </h2>
 <%= render :partial => 'form' %>